language: go
go:
  - 1.8.1
services:
  - docker
before_install:
  - cd $HOME/gopath/src/
  - git clone --depth=50 --branch=master https://github.com/zainul-ma/customer.git customer
  - cd $HOME/gopath/src/customer
  - echo 'export GOENV=testCi' >> ~/.bashrc
  - source ~/.bashrc
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls
install:
  - docker run -p 27017:27017 -d --name mongo mongo
  - docker run -p 5672:5672 -d --name rabbitmq rabbitmq
  - docker ps -a
  - wget https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm && chmod +x gpm && sudo mv gpm /usr/local/bin
  # - GOPATH=$HOME/gopath gometalinter --install
  - gpm install
  - ifconfig
script:
  - cd $HOME/gopath/
  - ls -lah
  - cd $HOME/gopath/src/customer
  - ls -lah
  - go env
  - pwd
  - go test ./...
#  - gometalinter ./...
  - cd $HOME/gopath/src/customer
  - overalls -project=$HOME/gopath/src/customer -covermode=count -debug
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci
# after_success:
  # - docker build -t apalahitunamanya2/blog .
  # - if [ "$TRAVIS_BRANCH" == "master" ]; then
  #   docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  #   docker push apalahitunamanya2/blog;
  #   fi
notifications:
  slack:
    rooms:
      - tnindo:rZLNlfCwMFJDF68W1CtvtGoLfWN4lSbmq#travis-ci
